### ISSUE TITLE
AttributeError: '_thread._local' object has no attribute 'hub'

### ISSUE THREAD

**Issue by lorien** [gevent/gevent#687]
I got the error

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/lorien/web/ppc/.env/lib/python3.4/site-packages/gevent/hub.py", line 333, in get_hub
    return _threadlocal.hub
AttributeError: '_thread._local' object has no attribute 'hub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 8, in func
    time.sleep(2)
  File "/home/lorien/web/ppc/.env/lib/python3.4/site-packages/gevent/hub.py", line 130, in sleep
    hub = get_hub()
  File "/home/lorien/web/ppc/.env/lib/python3.4/site-packages/gevent/hub.py", line 336, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "/home/lorien/web/ppc/.env/lib/python3.4/site-packages/gevent/hub.py", line 452, in __init__
    loop_class = _import(self.loop_class)
  File "/home/lorien/web/ppc/.env/lib/python3.4/site-packages/gevent/hub.py", line 365, in _import
    return _import(path[-1])
  File "/home/lorien/web/ppc/.env/lib/python3.4/site-packages/gevent/hub.py", line 382, in _import
    raise ImportError('Cannot import %r from %r' % (attr, oldx))
ImportError: Cannot import 'core' from <module 'gevent' from '/home/lorien/web/ppc/.env/lib/python3.4/site-packages/gevent/__init__.py'>
```

while running this code

```
from gevent.monkey import patch_all
patch_all(thread=False)
from threading import Thread
import time


def func():
    time.sleep(2)


def main():
    threads = []
    for x in range(2):
        th = Thread(target=func)
        th.start()
        threads.append(th)
    for th in threads:
        th.join()


if __name__ == '__main__':
    main()
```

CPython 3.4.1
gevent 1.1b6

What I am trying to do is to use gevent greenlets WITH threads. But I need native threads, not monkeypatched because I use pycurl inside threads that could not be monkeypatched.

**Comment by jamadden** [comment]
Thank you for your report. I believe this is fixed in master with 02a81bca56fe87ed074c1754d7225aa491f0e2f0. Can you confirm that? (I *think* the underlying issue is due to importing from a thread while the import lock is held.)

A fix for older versions of gevent is to make sure `gevent.get_hub` is called in the main thread before spawning background threads. Here, for example, if I make the following change, I cannot produce the error on 1.1b6:

```python
if __name__ == '__main__':
    import gevent
    gevent.get_hub()
    main()
```

**Comment by lorien** [comment]
Thank for quick response Jason.
The `gevent.get_hub()` hack works for me. BUT the 02a81bc does not. It still fails (with another exception) on the code I've submitted in my previous message.

The error is
```
$ time python test.py
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 8, in func
    time.sleep(2)
  File "/home/lorien/web/ppc/.env/src/gevent/gevent/hub.py", line 143, in sleep
    hub = get_hub()
  File "/home/lorien/web/ppc/.env/src/gevent/gevent/hub.py", line 343, in get_hub
    hub = _threadlocal.hub = hubtype(*args, **kwargs)
  File "/home/lorien/web/ppc/.env/src/gevent/gevent/hub.py", line 460, in __init__
    loop_class = _import(self.loop_class)
  File "/home/lorien/web/ppc/.env/src/gevent/gevent/hub.py", line 368, in _import
    return _import(path[-1])
  File "/home/lorien/web/ppc/.env/src/gevent/gevent/hub.py", line 385, in _import
    raise ImportError('Cannot import %r from %r' % (attr, oldx))
ImportError: Cannot import 'core' from <module 'gevent' from '/home/lorien/web/ppc/.env/src/gevent/gevent/__init__.py'>
```

I've isntalled gevent with `pip install -e git+https://github.com/gevent/gevent@02a81bca56fe87ed074c1754d7225aa491f0e2f0#egg=gevent`

**Comment by jamadden** [comment]
Hmm, ok. I can't reproduce that locally (OS X, CPython 3.4.3), and I added the same test case to run on Travis, where it also passes (Linux, CPython 3.4.2)---both platforms x86-64. I wonder if there's an issue with CPython 3.4.1, or some other platform difference?

**Comment by jamadden** [comment]
There might be some relevant output in 'python -vv test.py'

**Comment by jamadden** [comment]
I just reproduced it. Debugging.

**Comment by jamadden** [comment]
Ok, so this is basically a race condition with the import locks, explaining why it only manifests under certain conditions. Here's what I see in this scenario:

- Thread 1 executes `__import__('gevent.core')` (which is expected to both import `gevent.core` and return `gevent`). This places a placeholder entry for `gevent.core` into `sys.modules`. Thread 1 then drops the GIL to begin the actual import search.
- Thread 2 now acquires the GIL and executes that same import statement. Because of the placeholder entry in `sys.modules`, it returns immediately. 
- Thread 2 then executes `getattr('gevent', 'core')` which fails, because the actual work of importing `gevent.core` (in progress by Thread 1) has not yet finished. It raises the ImportError.
- Eventually Thread 1 finishes the import and reacquires the GIL, patches up `gevent` to have the `gevent.core` attribute, and continues on.

This scenario isn't possible in Python 2 (I think) because of its global import lock. Python 3 uses a more sophisticated system of per-module locks that apparently isn't totally bulletproof.

Note that if Thread 2 notices the existence of the `gevent.core` entry in `sys.modules` and uses it, it's not ready yet (Thread 1 isn't done) and so Thread 2 experiences a different set of confusing errors.

I'm not sure what to do about this, other than introducing our own global import lock for this function, or some unspecified refactoring to better handle the laziness. I'm not sure of the implications of either, especially since I'm hoping to get an RC1 out soon-ish.

**Comment by jamadden** [comment]
As far as I can tell, this particular special case is safe to go ahead and eagerly import.

**Comment by sibelius** [comment]
This is still happening on python 3.5

```python
Exception in thread pymongo_server_monitor_thread:
Traceback (most recent call last):
  File "roid/lib/python3.5/site-packages/eventlet/hubs/__init__.py", line 111, in get_hub
    hub = _threadlocal.hub
AttributeError: '_thread._local' object has no attribute 'hub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "roid/lib/python3.5/site-packages/eventlet/hubs/__init__.py", line 114, in get_hub
    _threadlocal.Hub
AttributeError: '_thread._local' object has no attribute 'Hub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "roid/lib/python3.5/site-packages/pymongo/periodic_executor.py", line 103, in _run
    time.sleep(self._min_interval)
  File "roid/lib/python3.5/site-packages/eventlet/greenthread.py", line 29, in sleep
    hub = hubs.get_hub()
  File "roid/lib/python3.5/site-packages/eventlet/hubs/__init__.py", line 116, in get_hub
    use_hub()
  File "roid/lib/python3.5/site-packages/eventlet/hubs/__init__.py", line 70, in use_hub
    mod = get_default_hub()
  File "roid/lib/python3.5/site-packages/eventlet/hubs/__init__.py", line 39, in get_default_hub
    return eventlet.hubs.epolls
AttributeError: module 'eventlet.hubs' has no attribute 'epolls'
```

**Comment by jamadden** [comment]
In the future please open a new issue.

However, what you report does not seem related to gevent. I only see `eventlet` in the traceback. `eventlet` is a completely different package.

**Comment by sibelius** [comment]
wrong repo, sorry
